version: '3'
services:
  minio:
    image: minio/minio
    networks:
      - traefik_public
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: 'lighthousex'
      MINIO_SECRET_KEY: 'JgTFKC6NaeDrVnv'
      GOOGLE_APPLICATION_CREDENTIALS: /credentials/outletgo-gcloud-service.json
    volumes:
      - ./credentials/outletgo-gcloud-service.json:/credentials/outletgo-gcloud-service.json
    command: minio gateway gcs voltaic-charter-173611
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.docker.network=traefik_public"
        - "traefik.frontend.rule=Host:files.outletego.com"

networks:
  traefik_public:
    external: true
