version: "3"

services:
  traefik:
    image: traefik
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG --configFile=/var/traefik/traefik.toml
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/var/traefik/traefik.toml 
      - ./acme:/etc/traefik/acme

    labels:
      - "traefik.enable=false"
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]                                                      
      restart_policy:
        condition: on-failure

networks:
  public:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
