################################################################
# Global configuration
################################################################
# Log level
logLevel = "DEBUG"
#
# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
defaultEntryPoints = ["http", "https"]
#
################################################################
# ACME (Let's Encrypt): automatic SSL
################################################################
[acme]

 email = "2256935429@qq.com"
# storageFile = "/etc/traefik/acme/acme.json"
 storage= "/etc/traefik/acme/acme.json"
 entryPoint = "https"
 onDemand = true
 OnHostRule = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/traefik/ca/214462692230331.pem"
      KeyFile = "/etc/traefik/ca/214462692230331.key"


################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]

# Web administration port
 address = ":8080"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
 endpoint = "unix:///var/run/docker.sock"

# Default domain used.
# Can be overridden by setting the "traefik.domain" label on a container.
# domain = "traefik"

# Enable watch docker changes
 watch = true
